#!/bin/bash

#livePlot -load srf-fe-ai-daq-test &
#exit

options="-span 2"

# Track RF cavity PVs
PREFIX="adamc:"
for suf in GSET PSET
do
  pvs=""
  for l in 1
  do
    for z in M N O P
    do
      for c in 1 2 3 4 5 6 7 8
      do
        pvs="$pvs ${PREFIX}R${l}${z}${c}${suf}"
      done
    done
  done
  livePlot $options -channels $pvs &
done

# Track JT positions
livePlot $options -channels "${PREFIX}CEV1L22JT" "${PREFIX}CEV1L23JT" "${PREFIX}CEV1L24JT" "${PREFIX}CEV1L25JT" &

# Track Radiation
#for suf in _gCur _nCur
#do
#  pvs=""
#  for id in 1L05 1L06 1L07 1L08 1L22 1L23 1L24 1L25 1L26
#  do
#    pvs="$pvs ${PREFIX}INX${id}${suf}"
#  done
#  livePlot $options -channels $pvs &
#done


