#!/bin/bash


if [ $# -ne 1 ] ; then
  echo "requires argument for linac number {1, 2}"
  exit 1
fi

l=$1
echo "..$l.."
if [ "$l" != "1" -a "$l" != "2" ] ; then
  echo "requires argument for linac number {1, 2}"
  exit 1
fi
#livePlot -load srf-fe-ai-daq-test &
#exit

options="-span 2"

# Track RF cavity PVs
PREFIX="adamc:"
for suf in GSET PSET
do
  pvs=""
  for z in M N O P
  do
    for c in 1 2 3 4 5 6 7 8
    do
      pvs="$pvs ${PREFIX}R${l}${z}${c}${suf}"
    done
  done
  livePlot $options -channels $pvs &
done


suffix="JT"
# Track JT positions
pvs=""
for z in 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
do
  pvs="$pvs ${PREFIX}CEV${l}L${z}JT"
done
livePlot $options -channel $pvs &
#livePlot $options -channels "${PREFIX}CEV1L22JT" "${PREFIX}CEV1L23JT" "${PREFIX}CEV1L24JT" "${PREFIX}CEV1L25JT" &

# Track Radiation
#for suf in _gCur _nCur
#do
#  pvs=""
#  for id in 1L05 1L06 1L07 1L08 1L22 1L23 1L24 1L25 1L26
#  do
#    pvs="$pvs ${PREFIX}INX${id}${suf}"
#  done
#  livePlot $options -channels $pvs &
#done


