#!/usr/csite/pubtools/bin/python3.11
import pandas as pd
import sys
import os

# Filename: where to find the file containing data generated by get-odvh.bash (e.g., R123,Value)
# margin: How much to add to the odvh values.
filename = sys.argv[1]
margin = float(sys.argv[2])

if not os.path.exists(filename):
  raise Exception(f"File not found: {filename}")

df = pd.read_csv(filename)
df.Value = df.Value + margin
df = df.set_index(df.Cavity)

print(df)
print(df.Value.to_json(orient="index", indent=2))
